version: '3.4'

networks:
  backendnet:    
  authnetwork:
  
services:
    backend:
        image: furlupe/deliverydeck_backend:latest
        depends_on:
            - db_backend
        ports:
            - "8081:80"
        networks:
            - backendnet
        
    auth:
        image: furlupe/deliverydeck_auth:latest
        depends_on:
            - db_auth
        ports:
            - "8080:80"
        networks:
            - authnetwork

    db_auth:
        image: postgres:alpine
        env_file: ./db_auth.env
        ports:
            - "5432"
        networks:
            - authnetwork

    db_backend:
        image: postgres:alpine
        env_file: ./db_backend.env
        ports:
            - "5432"
        networks:
            - backendnet